# Generated by Django 5.1.15 on 2026-07-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('raw_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('erased_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'visitor_pii',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('user_type', models.CharField(default='anonymous', max_length=16)),
                ('visitor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_bot', models.BooleanField(default=False)),
                ('is_confirmed_human', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('person_ref_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='referrals.referral')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'events',
                'indexes': [models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx'), models.Index(fields=['referral'], name='events_referra_a3c093_idx'), models.Index(fields=['visitor_id'], name='events_visitor_7d6b8c_idx'), models.Index(fields=['is_bot'], name='events_is_bot_7a62de_idx'), models.Index(fields=['is_confirmed_human'], name='events_is_conf_394b47_idx'), models.Index(fields=['timestamp'], name='events_timesta_ba2f67_idx')],
            },
        ),
    ]
