# Generated by Django 5.1.15 on 2026-07-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_clicknonce'),
        ('referrals', '0002_prospect_lead_prospect_prospects_email_f91804_idx_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(default='system', max_length=32),
        ),
        migrations.CreateModel(
            name='SyncHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_successful_zoho_sync_at', models.DateTimeField(blank=True, null=True)),
                ('zoho_state', models.CharField(choices=[('healthy', 'healthy'), ('degraded', 'degraded'), ('stalled', 'stalled'), ('no_sync', 'no_sync')], default='no_sync', max_length=16)),
                ('last_successful_wati_at', models.DateTimeField(blank=True, null=True)),
                ('wati_state', models.CharField(choices=[('healthy', 'healthy'), ('degraded', 'degraded'), ('stalled', 'stalled'), ('no_sync', 'no_sync')], default='no_sync', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sync_health',
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('links_created', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('landing_views', models.IntegerField(default=0)),
                ('redirects', models.IntegerField(default=0)),
                ('leads', models.IntegerField(default=0)),
                ('accounts_opened', models.IntegerField(default=0)),
                ('recomputed_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='referrals.referralprogram')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'daily_metrics',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'metric_date', 'program'), name='uq_daily_metric')],
            },
        ),
        migrations.CreateModel(
            name='DirtyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='referrals.referralprogram')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dirty_periods',
                'indexes': [models.Index(fields=['processed_at'], name='dirty_perio_process_b307ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('links_created', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('landing_views', models.IntegerField(default=0)),
                ('redirects', models.IntegerField(default=0)),
                ('leads', models.IntegerField(default=0)),
                ('accounts_opened', models.IntegerField(default=0)),
                ('recomputed_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='referrals.referralprogram')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'monthly_metrics',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'year', 'month', 'program'), name='uq_monthly_metric')],
            },
        ),
    ]
