# Generated by Django 5.1.15 on 2026-07-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('website', models.URLField(blank=True, default='')),
                ('status', models.CharField(default='active', max_length=20)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('brand_color', models.CharField(blank=True, default='', max_length=20)),
                ('reward_description', models.TextField(blank=True, default='')),
                ('terms_url', models.URLField(blank=True, default='')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='referrals.partner')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='ProgramRedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('match_condition', models.JSONField(blank=True, default=dict)),
                ('destination_url_template', models.TextField()),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='referrals.referralprogram')),
            ],
            options={
                'db_table': 'program_redirect_rules',
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status'], name='partners_status_6458e3_idx'),
        ),
        migrations.AddIndex(
            model_name='referralprogram',
            index=models.Index(fields=['status'], name='programs_status_1f33ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralprogram',
            constraint=models.UniqueConstraint(fields=('tenant', 'partner', 'name'), name='uq_program_tenant_partner_name'),
        ),
        migrations.AddIndex(
            model_name='programredirectrule',
            index=models.Index(fields=['program', 'priority'], name='program_red_program_8a6ab5_idx'),
        ),
    ]
