# Generated by Django 5.1.15 on 2026-07-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('lead_source', models.CharField(blank=True, default='', max_length=40)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'prospects',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('interested', 'interested'), ('kyc_started', 'kyc_started'), ('account_opened', 'account_opened'), ('rejected', 'rejected')], default='new', max_length=20)),
                ('status_source', models.CharField(blank=True, default='', max_length=20)),
                ('submitted_by', models.CharField(choices=[('friend', 'friend'), ('referrer', 'referrer')], default='friend', max_length=12)),
                ('consent', models.BooleanField(default=False)),
                ('zoho_lead_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('account_opened_at', models.DateTimeField(blank=True, null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='referrals.referral')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='referrals.prospect')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['email'], name='prospects_email_f91804_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['referral'], name='leads_referra_988fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_status_94f025_idx'),
        ),
    ]
