# Generated by Django 5.1.15 on 2026-07-06 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_prospect_lead_prospect_prospects_email_f91804_idx_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=64)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(default='active', max_length=20)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='referrals.partner')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='referrals.referralprogram')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['mobile'], name='customers_mobile_181b4b_idx'), models.Index(fields=['email'], name='customers_email_92e882_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'program', 'client_id'), name='uq_customer_program_client')],
            },
        ),
    ]
