# Generated by Django 5.1.15 on 2026-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='account_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='conversion_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='conversion_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='conversion_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='credited_referrer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
