# Generated by Django 5.1.15 on 2026-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_referral_account_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralprogram',
            name='disclosure_sequence',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='disclosure_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='regulator',
            field=models.CharField(choices=[('sebi_nse', 'SEBI / NSE'), ('irdai', 'IRDAI'), ('rbi', 'RBI'), ('other', 'Other')], default='sebi_nse', max_length=16),
        ),
    ]
