# Generated by Django 5.1.15 on 2026-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_referralprogram_disclosure_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consent_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, default='landing', max_length=32),
        ),
    ]
