# Generated by Django 5.1.15 on 2026-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_lead_consent_captured_at_lead_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gorefer_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
