# Generated by Django 5.1.15 on 2026-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_lead_gorefer_reference'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='zoho_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='zoho_sync_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='zoho_sync_status',
            field=models.CharField(choices=[('pending', 'pending'), ('synced', 'synced'), ('failed', 'failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='zoho_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['zoho_sync_status', 'zoho_sync_attempts'], name='leads_zoho_sy_ad9c22_idx'),
        ),
    ]
