# Generated by Django 5.1.15 on 2026-07-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_lead_zoho_last_error_lead_zoho_sync_attempts_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('referral_identity__isnull', False)), fields=('tenant', 'referral_identity', 'source'), name='uq_referral_tenant_identity_source'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('referral_identity__isnull', True), ('source', 'partner_direct')), fields=('tenant', 'source'), name='uq_referral_partner_direct_tenant'),
        ),
    ]
