# Generated by Django 5.1.15 on 2026-08-16 19:52

from django.db import migrations, models


def assert_no_cross_tenant_duplicates(apps, schema_editor):
    """T-161 pt 28: refuse to install the composite constraint over data that would
    already violate it. Trivially true with the single seeded tenant today, but this
    makes the assumption an enforced precondition rather than a comment."""
    from django.db.models import Count

    Partner = apps.get_model("referrals", "Partner")
    dupes = list(
        Partner.objects.values("tenant_id", "code").annotate(n=Count("id")).filter(n__gt=1)
    )
    if dupes:
        raise RuntimeError(
            f"cannot add uq_partner_tenant_code — existing cross-tenant duplicate "
            f"(tenant_id, code) rows: {dupes}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_referral_uq_referral_tenant_identity_source_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assert_no_cross_tenant_duplicates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_partner_tenant_code'),
        ),
    ]
