# Generated by Django 5.1.15 on 2026-07-21 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferrerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=64)),
                ('google_email', models.EmailField(blank=True, default='', max_length=254)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('bound_via', models.CharField(choices=[('otp', 'otp'), ('oauth_auto', 'oauth_auto'), ('admin_approval', 'admin_approval')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=16)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrer_accounts',
                'indexes': [models.Index(fields=['google_email'], name='referrer_ac_google__ce907e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'client_id'), name='uq_referrer_account_tenant_client')],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('oauth_mismatch', 'oauth_mismatch'), ('evidence', 'evidence')], max_length=20)),
                ('client_id', models.CharField(max_length=64)),
                ('registered_name', models.CharField(blank=True, default='', max_length=160)),
                ('mobile_entered', models.CharField(blank=True, default='', max_length=20)),
                ('google_email', models.EmailField(blank=True, default='', max_length=254)),
                ('evidence', models.BinaryField(blank=True, null=True)),
                ('evidence_content_type', models.CharField(blank=True, default='', max_length=60)),
                ('evidence_size', models.IntegerField(default=0)),
                ('evidence_purged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('decided_by', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referrer_verification_requests',
                'indexes': [models.Index(fields=['tenant', 'status'], name='referrer_ve_tenant__86b877_idx'), models.Index(fields=['client_id'], name='referrer_ve_client__efbcaf_idx')],
            },
        ),
    ]
