# Generated by Django 5.1.15 on 2026-08-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('referrals', '0009_referral_uq_referral_tenant_identity_source_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsLinkState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epoch', models.PositiveIntegerField(default=1)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='records_link_state', to='referrals.referralidentity')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'records_link_state',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'identity'), name='uq_records_link_state_tenant_identity')],
            },
        ),
    ]
