# Generated by Django 5.1.15 on 2026-08-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recordslinkstate'),
        ('referrals', '0009_referral_uq_referral_tenant_identity_source_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferrerShareOpener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default='')),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_opener', to='referrals.referralidentity')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referrer_share_opener',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'identity'), name='uq_referrer_share_opener_tenant_identity')],
            },
        ),
    ]
