# Generated by Django 5.1.15 on 2026-08-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_referrershareopener'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='onfile_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
