# Generated by Django 5.1.15 on 2026-08-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('min_records', models.PositiveIntegerField(default=0, help_text='Minimum referral records the recipient must have.')),
                ('activity_window_days', models.PositiveIntegerField(blank=True, help_text='Only consider activity within this many days (blank = no window limit).', null=True)),
                ('exclude_converted', models.BooleanField(default=True)),
                ('manual_include_mobiles', models.JSONField(blank=True, default=list, help_text='Mobile numbers always included, bypassing eligibility (JSON list of strings).')),
                ('manual_exclude_mobiles', models.JSONField(blank=True, default=list, help_text='Mobile numbers always excluded, overriding eligibility (JSON list of strings).')),
                ('max_msgs_per_24h', models.PositiveIntegerField(default=1)),
                ('max_msgs_per_72h', models.PositiveIntegerField(default=1)),
                ('max_msgs_per_7d', models.PositiveIntegerField(default=2)),
                ('send_days_mask', models.PositiveSmallIntegerField(default=31, help_text='Bitmask of allowed send days, bit0=Mon..bit6=Sun (see WEEKDAY_BITS).')),
                ('send_hour_ist', models.PositiveSmallIntegerField(default=9)),
                ('anchor_event_key', models.CharField(blank=True, default='', help_text="Symbolic event key naming what anchors the drip (e.g. 'record_created'). Config only — no code here consumes it.", max_length=60)),
                ('language_template_map', models.JSONField(blank=True, default=dict, help_text='Language code -> Meta template name, e.g. {"en": "gr_platform_..."}. Blank/missing language falls back to English.')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'messaging_campaigns',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessagingCampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('gap_days_from_previous', models.PositiveIntegerField(default=0, help_text='Whole days after the previous step (or the anchor, for step 1).')),
                ('language', models.CharField(default='en', max_length=5)),
                ('template_role', models.CharField(blank=True, default='', max_length=60)),
                ('template_name', models.CharField(blank=True, default='', help_text="Overrides the campaign's language_template_map for this step when set.", max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='campaigns.messagingcampaign')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'messaging_campaign_steps',
                'ordering': ['campaign_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='messagingcampaign',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uq_messaging_campaign_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='messagingcampaignstep',
            constraint=models.UniqueConstraint(fields=('campaign', 'order'), name='uq_campaign_step_order'),
        ),
    ]
