# Generated by Django 5.1.15 on 2026-08-14 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('language', models.CharField(default='en', max_length=5)),
                ('record_created_at', models.DateTimeField(help_text="The referral record's creation instant — the drip's anchor event.")),
                ('source', models.CharField(default='zoho', max_length=20)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'synced_referrers',
            },
        ),
        migrations.CreateModel(
            name='ScheduledCampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('anchor_at', models.DateTimeField()),
                ('fire_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('skipped', 'skipped'), ('failed', 'failed')], default='scheduled', max_length=12)),
                ('dedupe_key', models.CharField(max_length=220, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=160)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='campaigns.messagingcampaign')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_messages', to='campaigns.messagingcampaignstep')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to='campaigns.syncedreferrer')),
            ],
            options={
                'db_table': 'scheduled_campaign_messages',
            },
        ),
        migrations.AddIndex(
            model_name='syncedreferrer',
            index=models.Index(fields=['active'], name='synced_refe_active_23e45e_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedreferrer',
            index=models.Index(fields=['mobile'], name='synced_refe_mobile_d11891_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncedreferrer',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_id'), name='uq_synced_referrer_tenant_client_id'),
        ),
        migrations.AddIndex(
            model_name='scheduledcampaignmessage',
            index=models.Index(fields=['status', 'fire_at'], name='scheduled_c_status_355cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledcampaignmessage',
            index=models.Index(fields=['mobile'], name='scheduled_c_mobile_155d09_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledcampaignmessage',
            index=models.Index(fields=['campaign', 'mobile'], name='scheduled_c_campaig_554294_idx'),
        ),
    ]
