# Generated by Django 5.1.15 on 2026-07-06 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0002_prospect_lead_prospect_prospects_email_f91804_idx_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_role', models.CharField(choices=[('office', 'office'), ('prospect', 'prospect'), ('referrer', 'referrer')], max_length=16)),
                ('recipient_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('template', models.CharField(max_length=100)),
                ('category', models.CharField(default='UTILITY', max_length=16)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('accepted', 'accepted'), ('delivered', 'delivered'), ('read', 'read'), ('failed', 'failed'), ('skipped', 'skipped')], default='queued', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('meta_error_code', models.IntegerField(blank=True, null=True)),
                ('failure_classification', models.CharField(blank=True, default='', max_length=120)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=120)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='referrals.referral')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['status'], name='notificatio_status_fce6f5_idx'), models.Index(fields=['recipient_role'], name='notificatio_recipie_024348_idx')],
            },
        ),
    ]
