# Generated by Django 5.1.15 on 2026-07-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('referrals', '0004_referral_account_opened_at_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoDeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.IntegerField(default=1)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'zoho_dead_letter',
            },
        ),
        migrations.CreateModel(
            name='ZohoSyncIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=40)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'zoho_sync_idempotency',
            },
        ),
        migrations.CreateModel(
            name='ZohoSyncWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_event_id', models.CharField(blank=True, default='', max_length=120)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'zoho_sync_watermark',
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opener_zerodha_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('zoho_lead_id', models.CharField(blank=True, default='', max_length=64)),
                ('opener_name', models.CharField(blank=True, default='', max_length=120)),
                ('referrer_client_id', models.CharField(blank=True, default='', max_length=64)),
                ('account_opened_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='account_opened', max_length=40)),
                ('reward_status', models.CharField(blank=True, default='', max_length=40)),
                ('source_origin', models.CharField(default='zoho', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='referrals.referralprogram')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='referrals.referral')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'conversions',
                'indexes': [models.Index(fields=['referrer_client_id'], name='conversions_referre_8763dc_idx'), models.Index(fields=['account_opened_at'], name='conversions_account_411789_idx'), models.Index(fields=['is_reversed'], name='conversions_is_reve_b1ef40_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('opener_zerodha_account_id__gt', '')), fields=('tenant', 'opener_zerodha_account_id'), name='uq_conversion_opener_account'), models.UniqueConstraint(condition=models.Q(('zoho_lead_id__gt', '')), fields=('tenant', 'zoho_lead_id'), name='uq_conversion_zoho_lead')],
            },
        ),
    ]
