# Generated by Django 5.1.15 on 2026-07-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_zohodeadletter_zohosyncidempotency_zohosyncwatermark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoWebhookNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'zoho_webhook_nonce',
                'indexes': [models.Index(fields=['created_at'], name='zoho_webhoo_created_573467_idx')],
            },
        ),
    ]
