# Generated by Django 5.1.15 on 2026-07-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_zohowebhooknonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='template_params',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
