# Generated by Django 5.1.15 on 2026-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_notification_template_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='adapter_kind',
            field=models.CharField(blank=True, choices=[('live', 'live'), ('log_only', 'log_only')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('accepted', 'accepted'), ('delivered', 'delivered'), ('read', 'read'), ('failed', 'failed'), ('skipped', 'skipped'), ('simulated_delivered', 'simulated_delivered')], default='queued', max_length=20),
        ),
    ]
