# Generated by Django 5.1.15 on 2026-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_notification_adapter_kind_alter_notification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatiWebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=40)),
                ('event_key', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wati_webhook_receipt',
                'indexes': [models.Index(fields=['created_at'], name='wati_webhoo_created_7498b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'event_key'), name='uniq_wati_receipt_endpoint_event')],
            },
        ),
    ]
