# Generated by Django 5.1.15 on 2026-07-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'config_central',
            },
        ),
        migrations.CreateModel(
            name='ConfigGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_global', to='tenants.tenant')),
            ],
            options={
                'db_table': 'config_global',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uq_config_global_tenant_key')],
            },
        ),
        migrations.CreateModel(
            name='ConfigUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('user_id', models.BigIntegerField()),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_user', to='tenants.tenant')),
            ],
            options={
                'db_table': 'config_user',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user_id', 'key'), name='uq_config_user_tenant_user_key')],
            },
        ),
    ]
