# Generated by Django 5.1.15 on 2026-07-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0009_referral_uq_referral_tenant_identity_source_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(max_length=40)),
                ('offset_minutes', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('session', 'session (free-form, in 24h window)'), ('template', 'template (approved, works out of window)')], default='session', max_length=10)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_hi', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('only_if_window_open', models.BooleanField(default=True)),
                ('stop_on_reply', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=100)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'followup_rules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FollowupWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=20)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'followup_windows',
            },
        ),
        migrations.CreateModel(
            name='ScheduledFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=20)),
                ('pref_lang', models.CharField(default='en', max_length=5)),
                ('fire_at', models.DateTimeField()),
                ('window_opened_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('skipped', 'skipped'), ('failed', 'failed')], default='scheduled', max_length=12)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('source_event', models.CharField(blank=True, default='', max_length=40)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=160)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='referrals.prospect')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled', to='followups.followuprule')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scheduled_followups',
            },
        ),
        migrations.AddIndex(
            model_name='followuprule',
            index=models.Index(fields=['enabled'], name='followup_ru_enabled_95900e_idx'),
        ),
        migrations.AddConstraint(
            model_name='followuprule',
            constraint=models.UniqueConstraint(fields=('tenant', 'step_key'), name='uq_followup_rule_tenant_step'),
        ),
        migrations.AddConstraint(
            model_name='followupwindow',
            constraint=models.UniqueConstraint(fields=('tenant', 'mobile'), name='uq_followup_window_tenant_mobile'),
        ),
        migrations.AddIndex(
            model_name='scheduledfollowup',
            index=models.Index(fields=['status', 'fire_at'], name='scheduled_f_status_47c19a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledfollowup',
            index=models.Index(fields=['mobile'], name='scheduled_f_mobile_a580a3_idx'),
        ),
    ]
