# Generated by Django 5.1.15 on 2026-08-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorCallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('slot', models.CharField(choices=[('9-12', '9 AM - 12 PM'), ('12-3', '12 PM - 3 PM'), ('3-6', '3 PM - 6 PM')], max_length=10)),
                ('request_date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_callback_request', to='followups.scheduledfollowup')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'advisor_callback_requests',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'mobile', 'slot', 'request_date'), name='uq_advisor_callback_tenant_mobile_slot_date')],
            },
        ),
    ]
