# Generated by Django 5.1.15 on 2026-07-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.CharField(max_length=64)),
                ('recipient', models.CharField(blank=True, default='', max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=64)),
                ('channel', models.CharField(blank=True, default='', max_length=20)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=120)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('verified', 'verified'), ('expired', 'expired'), ('exhausted', 'exhausted'), ('superseded', 'superseded')], default='active', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'otp_challenges',
                'indexes': [models.Index(fields=['tenant', 'identity', 'status'], name='otp_challen_tenant__def13b_idx'), models.Index(fields=['expires_at'], name='otp_challen_expires_ec0c81_idx')],
            },
        ),
    ]
